repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
        exclude: README.md|docs/
    -   id: end-of-file-fixer
        exclude: README.md|docs/
    -   id: trailing-whitespace
        exclude: README.md|docs/

- repo: local
  hooks:
    - id: make-format
      name: Python - autoflake, isort, black
      entry: bash -c 'make format'
      language: system
      files: \.(py|ipynb)$
      pass_filenames: false
    - id: make-docs
      name: Generate docs if they are not up to date
      entry: bash -c 'make docs'
      language: system
      always_run: True
      pass_filenames: false
    - id: make-readme
      name: Generate readme from ipynb...
      entry: bash -c 'make readme'
      files: \.(py|ipynb)$|^README\.md$
      language: system
      pass_filenames: false
